import React,{FormEvent,useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{AlertTriangle,Lightbulb,LogOut,MessageCircle,Send,ShieldCheck}from'lucide-react';
import{api,Me,Message,Space,AdminUser,AdminClass,setToken}from'./api'; import'./styles.css';

const ROLES=[['ELEVE','Élève'],['PROFESSEUR','Professeur'],['ADMINISTRATION','Administration'],['ADMIN_PRINCIPAL','Admin principal']] as const;
const SPACE_TYPES=[['CLASSE','Groupe de classe'],['MATIERE','Groupe matière'],['GENERAL_ELEVES','Général élèves'],['PERSONNEL','Personnel']] as const;

function Admin({close}:{close:()=>void}){
const[classes,setClasses]=useState<AdminClass[]>([]);const[users,setUsers]=useState<AdminUser[]>([]);
const[tab,setTab]=useState<'classe'|'compte'|'espace'>('compte');
const[msg,setMsg]=useState('');const[err,setErr]=useState('');
async function reload(){setClasses(await api<AdminClass[]>('/admin/classes'));setUsers(await api<AdminUser[]>('/admin/users'))}
useEffect(()=>{reload()},[]);
const[className,setClassName]=useState('');
async function createClasse(e:FormEvent){e.preventDefault();setErr('');setMsg('');try{await api('/admin/classes',{method:'POST',body:JSON.stringify({nom:className})});setClassName('');setMsg('Classe créée.');await reload()}catch(x){setErr((x as Error).message)}}
const[uIdentifiant,setUIdentifiant]=useState('');const[uNom,setUNom]=useState('');const[uRole,setURole]=useState<string>('ELEVE');const[uClasse,setUClasse]=useState('');const[uPass,setUPass]=useState('');
async function createUser(e:FormEvent){e.preventDefault();setErr('');setMsg('');try{await api('/admin/users',{method:'POST',body:JSON.stringify({identifiant:uIdentifiant,nomAffichage:uNom,role:uRole,classeId:uRole==='ELEVE'?uClasse:null,motDePasseInitial:uPass})});setUIdentifiant('');setUNom('');setUPass('');setMsg(`Compte "${uIdentifiant}" créé.`);await reload()}catch(x){setErr((x as Error).message)}}
const[eNom,setENom]=useState('');const[eType,setEType]=useState<string>('CLASSE');const[eClasse,setEClasse]=useState('');const[eMembres,setEMembres]=useState<string[]>([]);
function toggleMembre(id:string){setEMembres(m=>m.includes(id)?m.filter(x=>x!==id):[...m,id])}
async function createEspace(e:FormEvent){e.preventDefault();setErr('');setMsg('');try{await api('/admin/spaces',{method:'POST',body:JSON.stringify({nom:eNom,type:eType,classeId:(eType==='CLASSE'||eType==='MATIERE')?eClasse:null,membres:eMembres.map(id=>({utilisateurId:id,moderateur:false}))})});setENom('');setEMembres([]);setMsg('Espace créé.');await reload()}catch(x){setErr((x as Error).message)}}
return <div className="modal"><section className="admin-panel"><button className="close" onClick={close}>×</button><h2>Administration</h2>
<nav className="admin-tabs"><button className={tab==='compte'?'active':''} onClick={()=>setTab('compte')}>Comptes</button><button className={tab==='classe'?'active':''} onClick={()=>setTab('classe')}>Classes</button><button className={tab==='espace'?'active':''} onClick={()=>setTab('espace')}>Espaces</button></nav>
{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}
{tab==='classe'&&<form onSubmit={createClasse}><label>Nom de la classe<input value={className} onChange={e=>setClassName(e.target.value)} placeholder="ex. 3e A" required/></label><button>Créer la classe</button>
<h3>Classes existantes</h3><ul>{classes.map(c=><li key={c.id}>{c.nom}</li>)}</ul></form>}
{tab==='compte'&&<form onSubmit={createUser}>
<label>Identifiant<input value={uIdentifiant} onChange={e=>setUIdentifiant(e.target.value)} placeholder="ex. dupont.j" required/></label>
<label>Nom affiché<input value={uNom} onChange={e=>setUNom(e.target.value)} placeholder="ex. Jean Dupont" required/></label>
<label>Rôle<select value={uRole} onChange={e=>setURole(e.target.value)}>{ROLES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
{uRole==='ELEVE'&&<label>Classe<select value={uClasse} onChange={e=>setUClasse(e.target.value)} required><option value="">— Choisir —</option>{classes.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label>}
<label>Mot de passe initial<input type="text" value={uPass} onChange={e=>setUPass(e.target.value)} minLength={12} placeholder="12 caractères minimum" required/></label>
<button>Créer le compte</button>
<h3>Comptes existants ({users.length})</h3><ul className="admin-list">{users.map(u=><li key={u.id}>{u.nom_affichage} <small>— {u.identifiant} — {ROLES.find(r=>r[0]===u.role)?.[1]}{!u.actif&&' (suspendu)'}</small></li>)}</ul>
</form>}
{tab==='espace'&&<form onSubmit={createEspace}>
<label>Nom de l'espace<input value={eNom} onChange={e=>setENom(e.target.value)} placeholder="ex. Maths — 3e A" required/></label>
<label>Type<select value={eType} onChange={e=>setEType(e.target.value)}>{SPACE_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
{(eType==='CLASSE'||eType==='MATIERE')&&<label>Classe liée<select value={eClasse} onChange={e=>setEClasse(e.target.value)} required><option value="">— Choisir —</option>{classes.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label>}
<label>Membres</label><div className="admin-members">{users.map(u=><label key={u.id} className="checkline"><input type="checkbox" checked={eMembres.includes(u.id)} onChange={()=>toggleMembre(u.id)}/>{u.nom_affichage} <small>({ROLES.find(r=>r[0]===u.role)?.[1]})</small></label>)}</div>
<button disabled={eMembres.length===0}>Créer l'espace</button>
</form>}
</section></div>}

function Login({onDone,initError}:{onDone:()=>void;initError?:string}){const[err,setErr]=useState(initError??'');const[busy,setBusy]=useState(false);
useEffect(()=>{if(initError)setErr(initError)},[initError]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const f=new FormData(e.currentTarget);try{const r=await api<{token:string}>('/auth/login',{method:'POST',body:JSON.stringify({identifiant:f.get('identifiant'),password:f.get('password')})});setToken(r.token);onDone()}catch(x){setErr((x as Error).message)}finally{setBusy(false)}}
return <main className="login"><section className="login-card"><div className="brand-mark"><ShieldCheck/></div><p className="eyebrow">LYCÉE PRIVÉ LABAÏKA · NIAOGHO</p><h1>Labaïka <span>SOURA</span></h1><p className="muted">L'espace d'échange sûr de notre communauté scolaire.</p><form onSubmit={submit}><label>Identifiant<input name="identifiant" autoComplete="username" required/></label><label>Mot de passe<input name="password" type="password" autoComplete="current-password" minLength={8} required/></label>{err&&<p className="error" role="alert">{err}</p>}<button disabled={busy}>{busy?'Connexion…':'Se connecter'}</button></form><small>Compte fourni exclusivement par l'établissement</small></section></main>}

function Ideas({close}:{close:()=>void}){const[text,setText]=useState('');const[code,setCode]=useState('');const[err,setErr]=useState('');async function send(){try{const t=await api<{token:string}>('/ideas/token',{method:'POST'});const r=await api<{codeSuivi:string}>('/ideas',{method:'POST',body:JSON.stringify({token:t.token,contenu:text})});localStorage.setItem('soura_idee_suivi',r.codeSuivi);setCode(r.codeSuivi)}catch(x){setErr((x as Error).message)}}return <div className="modal"><section><button className="close" onClick={close}>×</button><Lightbulb className="idea-icon"/><h2>Boîte à idées anonyme</h2>{code?<><p>Idée déposée. Conservez ce code uniquement sur votre appareil :</p><strong className="tracking">{code}</strong></>:<><p className="muted">Votre identité, votre appareil et votre adresse IP ne sont pas associés à l'idée.</p><textarea value={text} onChange={e=>setText(e.target.value)} minLength={10} maxLength={4000} placeholder="Votre idée…"/>{err&&<p className="error">{err}</p>}<button disabled={text.trim().length<10} onClick={send}>Déposer anonymement</button><a className="danger" href="tel:+22657591995"><AlertTriangle/> Urgence ou danger — contacter l'établissement</a></>}</section></div>}

function App(){const[me,setMe]=useState<Me|null>();const[spaces,setSpaces]=useState<Space[]>([]);const[current,setCurrent]=useState<Space>();const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState('');const[ideas,setIdeas]=useState(false);const[admin,setAdmin]=useState(false);const[error,setError]=useState('');const[authError,setAuthError]=useState('');
async function load(){try{setAuthError('');const m=await api<Me>('/me');setMe(m);const s=await api<Space[]>('/spaces');setSpaces(s);if(s[0])setCurrent(s[0])}catch(x){setToken(null);setMe(null);setAuthError((x as Error).message)}}useEffect(()=>{load()},[]);useEffect(()=>{if(current)api<Message[]>(`/spaces/${current.id}/messages`).then(setMessages).catch(x=>setError(x.message))},[current]);async function send(e:FormEvent){e.preventDefault();if(!current||!text.trim())return;await api(`/spaces/${current.id}/messages`,{method:'POST',body:JSON.stringify({contenu:text})});setText('');setMessages(await api(`/spaces/${current.id}/messages`))}async function logout(){try{await api('/auth/logout',{method:'POST'})}finally{setToken(null);setMe(null)}}if(me===undefined)return <div className="splash">SOURA</div>;if(!me)return <Login onDone={load} initError={authError}/>;
return <div className="shell"><aside><header><div className="mini-mark">S</div><div><b>Labaïka SOURA</b><small>Messagerie scolaire</small></div></header><nav>{spaces.map(s=><button className={current?.id===s.id?'active':''} onClick={()=>setCurrent(s)} key={s.id}><MessageCircle/>{s.nom}<small>{s.type.replaceAll('_',' ')}</small></button>)}</nav><button className="ideas" onClick={()=>setIdeas(true)}><Lightbulb/> Boîte à idées</button>{me.role==='ADMIN_PRINCIPAL'&&<button className="ideas" onClick={()=>setAdmin(true)}><ShieldCheck/> Administration</button>}<footer><div className="avatar">{me.nom_affichage[0]}</div><div><b>{me.nom_affichage}</b><small>{me.role.replaceAll('_',' ')}</small></div><button aria-label="Déconnexion" onClick={logout}><LogOut/></button></footer></aside><main className="chat"><header><div><h2>{current?.nom??'Bienvenue'}</h2><p>{current?'Espace sécurisé de l’établissement':'Sélectionnez une discussion'}</p></div><span className="secure"><ShieldCheck/> Protégé</span></header><section className="messages">{error&&<p className="error">{error}</p>}{messages.map(m=><article key={m.id}><div className="avatar small">{m.auteur[0]}</div><div><b>{m.auteur}</b><time>{new Date(m.created_at).toLocaleString('fr-FR')}</time><p>{m.contenu}</p></div></article>)}</section>{current&&<form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Écrire un message…"/><button aria-label="Envoyer"><Send/></button></form>}</main>{ideas&&<Ideas close={()=>setIdeas(false)}/>}{admin&&<Admin close={()=>setAdmin(false)}/>}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);