import React,{FormEvent,useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{AlertTriangle,Lightbulb,LogOut,MessageCircle,Send,ShieldCheck}from'lucide-react';
import{api,Me,Message,Space}from'./api'; import'./styles.css';

function Login({onDone}:{onDone:()=>void}){const[err,setErr]=useState('');const[busy,setBusy]=useState(false);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const f=new FormData(e.currentTarget);try{await api('/auth/login',{method:'POST',body:JSON.stringify({identifiant:f.get('identifiant'),password:f.get('password')})});onDone()}catch(x){setErr((x as Error).message)}finally{setBusy(false)}}
return <main className="login"><section className="login-card"><div className="brand-mark"><ShieldCheck/></div><p className="eyebrow">LYCÉE PRIVÉ LABAÏKA · NIAOGHO</p><h1>Labaïka <span>SOURA</span></h1><p className="muted">L’espace d’échange sûr de notre communauté scolaire.</p><form onSubmit={submit}><label>Identifiant<input name="identifiant" autoComplete="username" required/></label><label>Mot de passe<input name="password" type="password" autoComplete="current-password" minLength={8} required/></label>{err&&<p className="error" role="alert">{err}</p>}<button disabled={busy}>{busy?'Connexion…':'Se connecter'}</button></form><small>Compte fourni exclusivement par l’établissement</small></section></main>}

function Ideas({close}:{close:()=>void}){const[text,setText]=useState('');const[code,setCode]=useState('');const[err,setErr]=useState('');async function send(){try{const t=await api<{token:string}>('/ideas/token',{method:'POST'});const r=await api<{codeSuivi:string}>('/ideas',{method:'POST',body:JSON.stringify({token:t.token,contenu:text})});localStorage.setItem('soura_idee_suivi',r.codeSuivi);setCode(r.codeSuivi)}catch(x){setErr((x as Error).message)}}return <div className="modal"><section><button className="close" onClick={close}>×</button><Lightbulb className="idea-icon"/><h2>Boîte à idées anonyme</h2>{code?<><p>Idée déposée. Conservez ce code uniquement sur votre appareil :</p><strong className="tracking">{code}</strong></>:<><p className="muted">Votre identité, votre appareil et votre adresse IP ne sont pas associés à l’idée.</p><textarea value={text} onChange={e=>setText(e.target.value)} minLength={10} maxLength={4000} placeholder="Votre idée…"/>{err&&<p className="error">{err}</p>}<button disabled={text.trim().length<10} onClick={send}>Déposer anonymement</button><a className="danger" href="tel:+22600000000"><AlertTriangle/> Urgence ou danger — contacter l’établissement</a></>}</section></div>}

function App(){const[me,setMe]=useState<Me|null>();const[spaces,setSpaces]=useState<Space[]>([]);const[current,setCurrent]=useState<Space>();const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState('');const[ideas,setIdeas]=useState(false);const[error,setError]=useState('');
async function load(){try{const m=await api<Me>('/me');setMe(m);const s=await api<Space[]>('/spaces');setSpaces(s);if(s[0])setCurrent(s[0])}catch{setMe(null)}}useEffect(()=>{load()},[]);useEffect(()=>{if(current)api<Message[]>(`/spaces/${current.id}/messages`).then(setMessages).catch(x=>setError(x.message))},[current]);async function send(e:FormEvent){e.preventDefault();if(!current||!text.trim())return;await api(`/spaces/${current.id}/messages`,{method:'POST',body:JSON.stringify({contenu:text})});setText('');setMessages(await api(`/spaces/${current.id}/messages`))}async function logout(){await api('/auth/logout',{method:'POST'});setMe(null)}if(me===undefined)return <div className="splash">SOURA</div>;if(!me)return <Login onDone={load}/>;
return <div className="shell"><aside><header><div className="mini-mark">S</div><div><b>Labaïka SOURA</b><small>Messagerie scolaire</small></div></header><nav>{spaces.map(s=><button className={current?.id===s.id?'active':''} onClick={()=>setCurrent(s)} key={s.id}><MessageCircle/>{s.nom}<small>{s.type.replaceAll('_',' ')}</small></button>)}</nav><button className="ideas" onClick={()=>setIdeas(true)}><Lightbulb/> Boîte à idées</button><footer><div className="avatar">{me.nom_affichage[0]}</div><div><b>{me.nom_affichage}</b><small>{me.role.replaceAll('_',' ')}</small></div><button aria-label="Déconnexion" onClick={logout}><LogOut/></button></footer></aside><main className="chat"><header><div><h2>{current?.nom??'Bienvenue'}</h2><p>{current?'Espace sécurisé de l’établissement':'Sélectionnez une discussion'}</p></div><span className="secure"><ShieldCheck/> Protégé</span></header><section className="messages">{error&&<p className="error">{error}</p>}{messages.map(m=><article key={m.id}><div className="avatar small">{m.auteur[0]}</div><div><b>{m.auteur}</b><time>{new Date(m.created_at).toLocaleString('fr-FR')}</time><p>{m.contenu}</p></div></article>)}</section>{current&&<form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Écrire un message…"/><button aria-label="Envoyer"><Send/></button></form>}</main>{ideas&&<Ideas close={()=>setIdeas(false)}/>}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
